### ISSUE TITLE
[FEATURE] De-dent after appropriate statements

### ISSUE THREAD

**Issue by kbrose** [DSpeckhals/python-indent#20]
What statements should trigger a de-dent? I can think of the following:
- `return`
- `yield`
- `continue`
- `break`
- `raise` (?)

Are there times when it would be incorrect to dedent after such statements (assuming they were not found in a string, a comment, or as a substring of a different variable/statement such as `return_values()`)?

**Comment by kbrose** [comment]
Ref: https://github.com/atom/language-python/pull/140

**Comment by DSpeckhals** [comment]
It looks like there is an open pull request in language-python that would solve this, so I'm closing this.
