### ISSUE TITLE
Brackets after closing parenthesis

### ISSUE THREAD

**Issue by jfiksel** [DSpeckhals/python-indent#32]
This is an awesome package! I'm actually trying to use it for writing R code, which recommends a similar indentation style. However, one difference between R and Python is that R uses brackets in function definitions. So I would start out with
```
f <- function(x,
              y){}
```

Where the `{}` is automatically created when I type `{`. My cursor would now be between the two brackets, and when I press enter I would like the following to happen: 

```
f <- function(x,
              y){
 |
}
```

With the `|` marking the cursor position. However, it ends up like:

```
f <- function(x,
              y){
|
                }
```
I'm honestly not familiar enough with javascript/this package to code this myself, but I think this would be an awesome edition, and could be helpful for lots of R users.

**Comment by DSpeckhals** [comment]
This package is very specific to Python. I'm not familiar with R, though I see what you're talking about. In truth, the Atom platform needs to determine indentation differently than it is now. This package was created to alleviate the pain until that happens (I remember reading that re-writing the syntax parser and indentation behavior was on the radar, but I haven't seen anything about it in a while).

Perhaps another solution is to make this package language-agnostic to handle any syntax that recommends indentation based on previous lines. I think I would either fork or rename python-indent if that were the case. 

Though python-indent is written in JavaScript, most of the logic is very generic. You could change some of the behavior to adapt to R by forking this repository, rename it to something specific to R, and then test it out. Sorry I couldn't be of more help!
