### ISSUE TITLE
Indentation breaks on empty strings inside brackets

### ISSUE THREAD

**Issue by mattniedelman** [DSpeckhals/python-indent#35]
Hi,
I've noticed that empty strings in lists/dictionaries break the indentation.  For example:
```
x = ['a', 'b', '', 'c']
    <cursor>

a = {'a' : 1,
     'b' : '',
     'c' : 2}
    <cursor>

```
indentation lines up to the opening bracket, instead of being reset as expected.  Hanging indent stops working generally for the rest of the file.

**Comment by DSpeckhals** [comment]
I think I know why this may be happening. I made a fix in PR #34 for triple-quoted comment strings that may have caused this regression. I'll take a look.
