### ISSUE TITLE
installation instruction

### ISSUE THREAD

**Issue by vincentvanhees** [DSpeckhals/python-indent#46]
Thanks for putting this online. A short description of how to install this, e.g. in the readme, would be good.

**Comment by kbrose** [comment]
@vincentvanhees I think most people probably encounter this package through the actual Atom program where it is clear how to install it. If you found this package some other way and want to record the steps you took to get it installed then I think submitting a PR for that would probably be welcomed!

**Comment by vincentvanhees** [comment]
I understand, I did not manage to get that far and ended up manually indenting the code. If I need it again in the future and figure out how then, I will do as you requested.

**Comment by kbrose** [comment]
1. Go to settings page
2. Click on Install (left navigation column)
3. Search for `python indent`
4. Find the `python-indent` package and click the blue install button.

![installation](https://user-images.githubusercontent.com/4053170/28324673-903e5310-6ba1-11e7-9dce-03c8518c351a.png)
