### ISSUE TITLE
Indentation double what it should be

### ISSUE THREAD

**Issue by kylebarron** [DSpeckhals/python-indent#58]
When I have "Hanging Indent Tabs" set to 1, and my indentation setting set to 4 spaces, this gives me a total of 8 spaces when creating a hanging indent. Likewise, when "Hanging Indent Tabs" is set to 2, this gives me a total of 16 spaces when creating a hanging indent. See the gif below for clarification.

When I deactivate this package, I have no indentation at all when creating a hanging indent, which leads me to believe that I'm not getting a "double effect" from using `python-indent` and `language-python`. 

![peek 2017-12-12 18-18](https://user-images.githubusercontent.com/15164633/33913715-f6baa28e-df68-11e7-9b58-000445f4aa46.gif)

There are no other packages interfering:
![image](https://user-images.githubusercontent.com/15164633/33913803-532c33de-df69-11e7-9f2d-5d440cfc7816.png)

My Atom specs are:

```
> atom --version
Atom    : 1.22.1
Electron: 1.6.15
Chrome  : 56.0.2924.87
Node    : 7.4.0
```

and using package version: 1.1.4.

**Comment by DSpeckhals** [comment]
Hmmm...I can't duplicate this error with the same version of Atom and the package. I'm guessing that some other package is causing the extra indent to be inserted. The key binding resolver log that you shared is helpful, but doesn't tell the full story. The top item `editor:newline` is what is used by this package. Other packages *may* hook into the same event.

If you are still having this issue, can you share your list of installed packages? We may be able to find the culprit there.

Thanks for letting me know about the problem!

**Comment by kylebarron** [comment]
I'm away from my work computer this week. I'll be able to give a better response next week, but I was able to ssh into it and get my list of installed packages:
```
Dev Packages (1) /home/kyle/.atom/dev/packages
└── language-markdown@0.25.1

Community Packages (87) /home/kyle/.atom/packages
├── Zen@0.18.0
├── aligner@1.2.4 (disabled)
├── aligner-javascript@1.3.0 (disabled)
├── aligner-python@1.1.0 (disabled)
├── atom-alignment@0.13.0
├── atom-beautify@0.30.9
├── atom-clock@0.1.15
├── atom-ide-ui@0.7.0 (disabled)
├── atom-material-syntax@1.0.8
├── atom-material-ui@2.0.6
├── atom-terminal@0.8.0
├── auto-detect-indentation@1.3.0
├── autoclose-html@0.23.0
├── autocomplete-R@0.6.0 (disabled)
├── autocomplete-bibtex@1.1.0
├── autocomplete-paths@2.12.1
├── autocomplete-python@1.10.5
├── busy-signal@1.4.3
├── change-case@0.6.5
├── color-picker@2.2.5
├── cson@2.0.1
├── css-snippets@1.1.0
├── docblockr@0.13.4
├── editor-stats@0.17.0
├── editorconfig@2.2.2
├── file-icons@2.1.15
├── fonts@3.0.3
├── git-control@0.9.0
├── git-plus@7.10.0
├── git-time-machine@1.5.9
├── grammar-token-limit@0.1.1
├── highlight-line@0.12.0 (disabled)
├── highlight-selected@0.13.1
├── hydrogen@2.2.0
├── hydrogen-launcher@1.2.1
├── indent-guide-improved@1.4.13
├── ink@0.7.11 (disabled)
├── insert-timestamp@0.2.4
├── intentions@1.1.5
├── julia-client@0.6.6 (disabled)
├── language-julia@0.14.0
├── language-latex@1.1.1
├── language-liquid@0.6.0
├── language-markdown@0.25.1
├── language-matlab@0.2.1
├── language-pfm@0.82.0 (disabled)
├── language-r@0.4.2
├── language-restructuredtext@1.1.0
├── language-sas@0.2.4
├── language-stata@1.3.0
├── latex@0.49.0
├── latex-completions@0.3.3
├── latexer@0.3.0 (disabled)
├── linter@2.2.0
├── linter-flake8@2.3.0 (disabled)
├── linter-shellcheck@1.4.6
├── linter-ui-default@1.6.10 (disabled)
├── linter-write-good@0.9.0 (disabled)
├── markdown-preview-plus@2.4.16
├── markdown-writer@2.7.3
├── minimap@4.29.7
├── minimap-bookmarks@0.4.2
├── minimap-cursorline@0.2.0 (disabled)
├── minimap-find-and-replace@4.5.2
├── minimap-git-diff@4.3.1
├── minimap-highlight-selected@4.6.1
├── minimap-pigments@0.2.2 (disabled)
├── minimap-selection@4.5.0
├── minimap-split-diff@0.3.7
├── pdf-view@0.61.0
├── pigments@0.40.2
├── platformio-ide-terminal@2.7.0
├── project-manager@3.3.5
├── python-indent@1.1.4 (disabled)
├── python-tools@0.6.9
├── qolor@0.4.2
├── regex-railroad-diagram@0.19.4
├── remote-edit@1.9.0
├── script@3.18.0
├── sort-lines@0.18.0
├── split-diff@1.5.1
├── stata-exec@1.2.1
├── teletype@0.4.0 (disabled)
├── toggle-quotes@1.1.0
├── tree-view-git-status@1.4.0
├── wakatime@7.0.4
└── wordcount@2.10.4
```

**Comment by kbrose** [comment]
That `indentation` package looks mighty suspicious judging by its name. Could you try turning that off and seeing if the behavior still happens?

**Comment by kylebarron** [comment]
I'm not sure which package you're referring to. I turned off `python-tools`, `auto-detect-indentation`, and even `autocomplete-python` and I'm still having the issue. The `intentions` package should be completely different.

Is there a way to do deeper debugging in Atom than the key binding resolver?

Here's my current list of installed and enabled packages:
```
> apm list --installed --enabled       
Dev Packages (1) /home/kyle/.atom/dev/packages
└── language-markdown@0.25.1

Community Packages (62) /home/kyle/.atom/packages
├── Hydrogen@2.2.1
├── Zen@0.18.0
├── atom-alignment@0.13.0
├── atom-beautify@0.30.9
├── atom-clock@0.1.15
├── atom-material-syntax@1.0.8
├── atom-material-ui@2.1.0
├── autoclose-html@0.23.0
├── autocomplete-bibtex@1.1.0
├── autocomplete-paths@2.12.1
├── busy-signal@1.4.3
├── change-case@0.6.5
├── color-picker@2.2.5
├── cson@2.0.1
├── docblockr@0.13.4
├── editor-stats@0.17.0
├── editorconfig@2.2.2
├── file-icons@2.1.15
├── fonts@3.0.3
├── git-plus@7.10.0
├── git-time-machine@1.5.9
├── grammar-token-limit@0.1.1
├── highlight-selected@0.13.1
├── hydrogen-launcher@1.2.1
├── insert-timestamp@0.2.4
├── intentions@1.1.5
├── language-julia@0.14.0
├── language-latex@1.1.1
├── language-liquid@0.6.0
├── language-markdown@0.25.1
├── language-r@0.4.2
├── language-restructuredtext@1.1.0
├── language-sas@0.2.4
├── language-stata@1.3.0
├── latex@0.49.0
├── latex-completions@0.3.3
├── linter@2.2.0
├── linter-shellcheck@1.4.6
├── markdown-preview-plus@2.4.16
├── markdown-writer@2.7.3
├── minimap@4.29.7
├── minimap-bookmarks@0.4.2
├── minimap-find-and-replace@4.5.2
├── minimap-git-diff@4.3.1
├── minimap-highlight-selected@4.6.1
├── minimap-selection@4.5.0
├── minimap-split-diff@0.3.7
├── pdf-view@0.62.0
├── pigments@0.40.2
├── platformio-ide-terminal@2.8.0
├── project-manager@3.3.5
├── python-indent@1.1.4
├── qolor@0.4.2
├── regex-railroad-diagram@0.19.4
├── remote-edit@1.9.0
├── sort-lines@0.18.0
├── split-diff@1.5.2
├── stata-exec@1.2.1
├── toggle-quotes@1.1.0
├── tree-view-git-status@1.4.0
├── wakatime@7.0.4
└── wordcount@2.10.4
```

**Comment by kbrose** [comment]
You're right, I misread intentions as indentations. My bad.

**Comment by kylebarron** [comment]
Is there a way to see what other packages might be using `editor:newline`? I have the same packages set up on my Ubuntu desktop and my Macbook, but my desktop has this issue and my Macbook doesn't.

**Comment by kbrose** [comment]
That's a good question. There's probably a way to set a breakpoint in the developer tools (`ctrl-shift-i`), but I don't know enough about JS/front-end tooling to know how to do that. Perhaps doing a recursive `grep` in your `.atom/packages` folder could find it?

**Comment by DSpeckhals** [comment]
I'm closing this due to this probably being a package conflict. Let me know if anything different comes up.
