### ISSUE TITLE
Multi-cursor indent

### ISSUE THREAD

**Issue by gasteigerjo** [DSpeckhals/python-indent#59]
The auto-indentation only works for the cursor placed last. It would be really nice if it indented for all cursors instead.
e.g.:
```
print("1"\cursor)
print("2"\cursor)
```

After hitting enter:
Current:
```
print("1"
)
print("2"
      )
```

Desired:
```
print("1"
      )
print("2"
      )
```

**Comment by DSpeckhals** [comment]
Thanks for filing the issue...sorry for the delay. This is an interesting. I'm not sure why it's not working correctly with multiple cursors, but I'm guessing there's some poor assumptions in the indentation logic in this package. I'll take a look.

**Comment by DSpeckhals** [comment]
Sorry this took so long to get to. I'm releasing a version of the package right now that handles this. Thanks for filing the issue!
