### ISSUE TITLE
Plugin doesn't work when Tree Sitter Parser are enabled

### ISSUE THREAD

**Issue by cbrnr** [DSpeckhals/python-indent#60]
Atom is currently testing Tree Sitter parsers, and the (experimental) setting can already be enabled in the core settings page. Since this will eventually be the default, I just wanted to give a heads up that python-indent is not working if these new parsers are enabled.

**Comment by DSpeckhals** [comment]
Thanks for the heads up. I will check this out, and see what we can do.

**Comment by cbrnr** [comment]
Wonderful! Works like a charm! Thanks @DSpeckhals, this is the most useful/essential Atom plugin for Python users!
