### ISSUE TITLE
Not working in .pyx/.pxd files

### ISSUE THREAD

**Issue by koenhelwegen** [DSpeckhals/python-indent#63]
Hi, great package! For a project where I compile a lot of code using Cython, I would love it if the functionality also works in files with a .pyx or .pxd extension

**Comment by DSpeckhals** [comment]
That shouldn't be difficult. I'll see what I can do.

**Comment by DSpeckhals** [comment]
This was resolved by a7f5ea6eaf162bee0406eb15991f7d238e325a93 and published. Thanks!

**Comment by koenhelwegen** [comment]
Thanks a lot, awesome!!
