### ISSUE TITLE
font

### ISSUE THREAD

**Issue by HaoyangFan96** [DSpeckhals/python-indent#64]
Thanks for this amazing package, really enjoy it :blush:

BTW, what is the font you use in the demo GIF? I like that font look better over the default of Atom uses on OSX

**Comment by DSpeckhals** [comment]
I'm glad it's helpful to you!

The font in the GIF is [Inconsolata](https://fonts.google.com/specimen/Inconsolata). I use it in my terminal emulator as well as in Atom.

**Comment by HaoyangFan96** [comment]
thanks
