### ISSUE TITLE
Break out python parsing into separate NPM package?

### ISSUE THREAD

**Issue by kbrose** [DSpeckhals/python-indent#65]
Hey @DSpeckhals! Can't believe it's been years since this extension was released.

In the https://github.com/Microsoft/vscode-python/issues/481 thread, you suggested it may make sense to break out the python parsing engine into a separate NPM package at some point if a similar indentation extension could be written for Visual Studio Code.

I have been playing around with an initial (extremely alpha) version of one (https://marketplace.visualstudio.com/items?itemName=KevinRose.vsc-python-indent). Right now I've just copy/pasted the parsing code over, but if there was an NPM package to depend on instead I'd be happy to refactor to depend on that.

There's no real need on my end, just thought I'd suggest it as a possibility in case you were interested.

**Comment by DSpeckhals** [comment]
Hi! I agree that it could be broken out. I'll have to look for some time to accomplish this, but I don't imagine it being that hard. Most of the core logic that you wrote is portable between editors, and is strictly a simple parser.
