### ISSUE TITLE
Incorrect behavior after update 1.17->1.21

### ISSUE THREAD

**Issue by Andykl** [DSpeckhals/python-indent#69]
![test_file1py](https://user-images.githubusercontent.com/27142420/57576162-63b60100-7462-11e9-8ce7-112d2c7ad283.gif)
![test_file2py](https://user-images.githubusercontent.com/27142420/57576163-644e9780-7462-11e9-8c3b-8a2e930884d1.gif)

My Atom:
```
Atom    : 1.36.1
Electron: 2.0.18
Chrome  : 61.0.3163.100
Node    : 8.9.3
```

**Comment by DSpeckhals** [comment]
Thanks for filing the issue. I'll take a look and see what needs to be fixed.
