### ISSUE TITLE
The Hanging-Type Indent Will Fail on Windows with CRLF Line Ending

### ISSUE THREAD

**Issue by xhchrn** [DSpeckhals/python-indent#82]
The hanging-type indent will fail if the file uses CRLF line ending, which is the default in Atom editor in Windows. After changing the line ending to LF, the package works fine.

I didn't see any hint about line ending selection in doc or README. It would be better this is fixed or emphasized in the doc.

**Comment by DSpeckhals** [comment]
Thanks for letting me know. I didn't think that there was anything that depended on line endings in the indentation logic, but apparently there is. I'll look into this.
